{% set name = "pedantic" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pedantic-{{ version }}.tar.gz
  sha256: 1b7d7e1c4e6377a395689db7983a9614fb6b659dac20fa6d52a93d5d04ba49a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - pedantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LostInDarkMath/pedantic-python-decorators
  summary: Some useful Python decorators for cleaner software development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikemhenry
